### PR TITLE
Create reusable Dockerfile

### PR DESCRIPTION
**Pull request by sodiray**
Hey @itsmetommy thanks for this repo and blog post. I couldn't stomach having separate directories for the same image so I worked a little docker startup magic to share one image. Thought it could be useful to you and others. 🍻

### CODE REVIEW

**Comment by sodiray** [comment]
Oh, it also automatically starts the cluster without needing to `exec` into a container.

**Comment by itsmetommy** [comment]
Looks and works great. Can you explain how all the images point to **redis-cluster-node** instead of **redis:latest**? I plan on merging once I update my website content.

**Comment by sodiray** [comment]
`redis-1` has the `build` instruction and the `image` name so its the one that builds the image, then the other services -- since the don't have a `build` instruction -- use that image. Lil trick to reduce all the building.

**Comment by itsmetommy** [comment]
Very neat. Thanks again!

**Pull request merged**
